=== tenzinnyeshi/CATtest/EmployeeSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Company">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Company" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Emp-name" type="xs:string"></xs:element>
							<xs:element name="Emp-age" type="xs:integer"></xs:element>
							<xs:element name="Emp-salary" type="MySal"></xs:element>
							<xs:element name="Emp-emailid" type="xs:string"></xs:element>
							<xs:element name="Emp-phonenum" type="xs:double"></xs:element>
							<xs:element name="Emp-designation" type="xs:string"></xs:element>
						</xs:sequence>
						<xs:attribute name="eid" type="xs:string" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="MySal">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="50000"></xs:minInclusive>
			<xs:maxInclusive value="2000000"></xs:maxInclusive>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== tenzinnyeshi/CATtest/EmployeeManagement.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type = "text/xsl" href="EmployeeXSDfile.xsl"?>
<Company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="EmployeeSchema.xsd">
	<Employee eid="E1">
		<Emp-name>Tenzin</Emp-name>
		<Emp-age>23</Emp-age>
		<Emp-salary>76000</Emp-salary>
		<Emp-emailid>tenzin@gmail.com</Emp-emailid>
		<Emp-phonenum>7018769320</Emp-phonenum>
		<Emp-designation>Programmer</Emp-designation>
	</Employee>
	<Employee eid="E2">
		<Emp-name>David</Emp-name>
		<Emp-age>25</Emp-age>
		<Emp-salary>65000</Emp-salary>
		<Emp-emailid>David@gmail.com</Emp-emailid>
		<Emp-phonenum>9898769320</Emp-phonenum>
		<Emp-designation>Marketer</Emp-designation>
	</Employee>
	<Employee eid="E3">
		<Emp-name>Johan</Emp-name>
		<Emp-age>26</Emp-age>
		<Emp-salary>150000</Emp-salary>
		<Emp-emailid>jonah@gmail.com</Emp-emailid>
		<Emp-phonenum>8374993848</Emp-phonenum>
		<Emp-designation>Accountant</Emp-designation>
	</Employee>
	<Employee eid="E4">
		<Emp-name>Natalie</Emp-name>
		<Emp-age>24</Emp-age>
		<Emp-salary>90000</Emp-salary>
		<Emp-emailid>natalie@gmail.com</Emp-emailid>
		<Emp-phonenum>9873647363</Emp-phonenum>
		<Emp-designation>Model</Emp-designation>
	</Employee>
	<Employee eid="E5">
		<Emp-name>Todd</Emp-name>
		<Emp-age>27</Emp-age>
		<Emp-salary>80000</Emp-salary>
		<Emp-emailid>todderic@gmail.com</Emp-emailid>
		<Emp-phonenum>9247362843</Emp-phonenum>
		<Emp-designation>Influencer</Emp-designation>
	</Employee>
	<Employee eid="E6">
		<Emp-name>Ilya</Emp-name>
		<Emp-age>29</Emp-age>
		<Emp-salary>57000</Emp-salary>
		<Emp-emailid>ilya@gmail.com</Emp-emailid>
		<Emp-phonenum>7634638363</Emp-phonenum>
		<Emp-designation>Producer</Emp-designation>
	</Employee>
	<Employee eid="E7">
		<Emp-name>Robert</Emp-name>
		<Emp-age>21</Emp-age>
		<Emp-salary>66000</Emp-salary>
		<Emp-emailid>robert@gmail.com</Emp-emailid>
		<Emp-phonenum>92637283474</Emp-phonenum>
		<Emp-designation>Developer</Emp-designation>
	</Employee>
	<Employee eid="E8">
		<Emp-name>Mundane</Emp-name>
		<Emp-age>27</Emp-age>
		<Emp-salary>175000</Emp-salary>
		<Emp-emailid>mundane@gmail.com</Emp-emailid>
		<Emp-phonenum>736476364</Emp-phonenum>
		<Emp-designation>Manager</Emp-designation>
	</Employee>
</Company>
